Mvc-project/Models/ErrorViewModel.cs
namespace Mvc_project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc-project/Models/Tables/BaseModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mvc_project.Models.Tables
{
    public class BaseModel
    {

        [Key , Required(ErrorMessage = "Id is required for further process.")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public int CreatedBy { get; set; }

       // [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        public DateTime ModifiedBy { get; set; }

        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime ModifiedDate { get; set; }
        public DateTime DeletedDate { get; set; }

    }
}

Mvc-project/Models/Tables/Cities.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mvc_project.Models.Tables
{
    public class Cities : BaseModel
    {
        [Required(ErrorMessage = "City name is required.")]
        public string CityName { get; set; }
        public int CountryId { get; set; }  //  FOREIGN KEY IS USED
        [ForeignKey("CountryId")]
        public virtual Country Country { get; set; }
    }
}

Mvc-project/Models/Tables/Country.cs
using System.ComponentModel.DataAnnotations;

namespace Mvc_project.Models.Tables
{
    public class Country : BaseModel
    {
        [Required(ErrorMessage = "Country name is required.")]
        public string CountryName { get; set; }
      
    }
}

Mvc-project/Models/Tables/Organization.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mvc_project.Models.Tables
{
    public class Organization : BaseModel
    {
        [Required(ErrorMessage = "Organization name is required.")]
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int CitiesId { get; set; }
        [ForeignKey("CitiesId")]
        public virtual Cities cities { get; set; } //FOREIGN KEY
        public string GoogleMapLocation { get; set; }


    }
}

Mvc-project/Models/Tables/Reviews.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mvc_project.Models.Tables
{
    public class Reviews : BaseModel
    {
        public int OrganizationId { get; set; } // foreign key
        public int UserId { get; set; } //foreign key

        [Required(ErrorMessage = "Rating is required.")]

        public double Rating { get; set; }
        public string ReviewText { get; set; }
        public DateTime ReviewDate { get; set; }

        [ForeignKey("OrganizationId")]
        public virtual Organization Organization { get; set; }
        [ForeignKey("UserId")]
        public virtual Users Users { get; set; }

    }
}

Mvc-project/Models/Tables/Users.cs
using System.ComponentModel.DataAnnotations;

namespace Mvc_project.Models.Tables
{
    public class Users : BaseModel
    {
        [Required(ErrorMessage = "User name is required.")]
        public string UserName { get; set; }
        [Required]
        public string UserEmail { get; set; }
        [Required]
        public string PasswordHash { get; set; }
        public string UserRole { get; set; } = string.Empty;
    }
}

Mvc-project/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc_project.Models;
using System.Diagnostics;

namespace Mvc_project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mvc-project/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;

namespace Mvc_project.Controllers
{
    public class HomePageController : Controller
    {
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
    }
}

Mvc-project/Controllers/PeopleReviewsController.cs
using Bloggie.Web.Data;
using Microsoft.AspNetCore.Mvc;

namespace Mvc_project.Controllers
{
    public class PeopleReviewsController : Controller
    {
        private BloggieDbContext bloggieDbContext;
        public PeopleReviewsController(BloggieDbContext bloggieDbContext)
        {
            this.bloggieDbContext = bloggieDbContext;
        }
        [HttpGet]
        public IActionResult Reviews()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SubmitTag()
        {

            var Rating= Request.Form["rating"];
            var Review_Text = Request.Form["reviewtext"];
            var Review_Date = Request.Form["rating_date"];

            return View("Reviews");
        }

    }
}

Mvc-project/Controllers/SearchbarController.cs
using Microsoft.AspNetCore.Mvc;

namespace Mvc_project.Controllers
{
    public class SearchbarController : Controller
    {
        [HttpGet]
        public IActionResult SearchBar()
        {
            return View();
        }
        [HttpPost]
        [ActionName("SearchBar")]
        public IActionResult SubmitTag()
        {
            var SearchBar = Request.Form["searchbar"];
            return View("SearchBar");
        }
    }
}

Mvc-project/Controllers/UserLoginController.cs
using Bloggie.Web.Data;
using Microsoft.AspNetCore.Mvc;
using Mvc_project.Models.Tables;

namespace Mvc_project.Controllers
{
    public class UserLoginController : Controller
    {
        private BloggieDbContext bloggieDbContext;
        public UserLoginController(BloggieDbContext bloggieDbContext)
        {
            this.bloggieDbContext = bloggieDbContext;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Login")]
        public IActionResult Login(Users addTagRequest)
        {
            Users login = new Users()
            {
                UserEmail = addTagRequest.UserEmail,
                PasswordHash = addTagRequest.PasswordHash
            };


            var user = bloggieDbContext.Users.FirstOrDefault(u => u.UserEmail == login.UserEmail);
            if (user != null)
            {
                if (user.PasswordHash != login.PasswordHash)
                {
                    ViewBag.errormessage = "not a valid user";
                    return View();
                }
                else
                {
                    return View("index", "Home");
                }
            }
            else
            {
                ViewBag.errormessage = "not a valid user";
            }

            bloggieDbContext.Users.Add(login);
            bloggieDbContext.SaveChanges();

            return View("Login");
        }
    }
}

Mvc-project/Controllers/UserRefistrationController.cs
using Bloggie.Web.Data;
using Microsoft.AspNetCore.Mvc;
using Mvc_project.Models.Tables;

namespace Mvc_project.Controllers
{
    public class UserRefistrationController : Controller
    {
        private BloggieDbContext bloggieDbContext;
        public UserRefistrationController(BloggieDbContext bloggieDbContext)
        {
            this.bloggieDbContext=bloggieDbContext;
        }


        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Registration")]
        public IActionResult SumbitTag ()
        {
            Users user =new Users();
            user.UserName = Request.Form["name"];
            user.UserEmail= Request.Form["email"];
            user.PasswordHash= Request.Form["password"];

            bloggieDbContext.Users.Add(user);
            bloggieDbContext.SaveChanges();


            return View("Registration");
        }
    }
}

Mvc-project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc-project/Views/HomePage/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="bg-secondary bg-opacity-10 pu-2">
    <div class="container">
        <h1>
            Add Home Page Information
        </h1>
    </div>

</div>

Mvc-project/Views/OrganizationController1/Organization.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class=" bg-secondary bg-opacity-10 py-3">
    <div class="container">
        <h2>ORGANIZATION DATA</h2>
    </div>
</div>

<div class="py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-label" id="name" name="name" />
        </div>
        <div class="mb-3">
            <label class="form-label">Adress</label>
            <input type="text" class="form-label" id="adress" name="adress" />
        </div>
        <div class="mb-3">
            <label class="form-label">Phone</label>
            <input type="text" class="form-label" id="phone" name="phone" />
        </div>
        <div class="mb-3">
            <label class="form-label">Google Map Location</label>
            <input type="text" class="form-label" id="googlemaplocation" name="googlemaplocation" />
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

Mvc-project/Views/PeopleReviews/Reviews.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="bg-secondary bg-opacity-10 py-3">
    <div class="container">
        <h2>Enter Your Reviews</h2>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">ID</label>
            <input type="text" value="" class="form-control" id="id" name="id" />
        </div>
        <div class="mb-3">
            <label class="form-label">Rating</label>
            <input type="text" value="" class="form-control" id="rating" name="rating" />
        </div>
        <div class="mb-3">
            <label class="form-label">Review_Text</label>
            <input type="text" value="" class="form-control" id="review_text" name="review_text" />
        </div>
        <div class="mb-3">
            <label class="form-label">Review_Date</label>
            <input type="text" value="" class="form-control" id="review_date" name="review_date" />
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

Mvc-project/Views/Searchbar/SearchBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="bg-secondary bg-opacity-10 py-3">
    <div class="container">
        <h2>Enter You Can Easily DO Searching Here</h2>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">SearchBar</label>
            <input type="text" value="" class="form-control" id="searchbar" name="searchbar" />
        </div>
        
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

Mvc-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc_project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc_project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc_project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Home Page
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="HomePage" asp-action="Add">Page-view</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                User Registration
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="UserRefistration" asp-action="Registration">Registration-Form</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                User Login
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="UserLogin" asp-action="Login">Login</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Organization
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Organization" asp-action="Organization">Organization </a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Organization" asp-action="Organization">Organization List</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Organization" asp-action="Organization">Organization Details</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Search Results
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="SearchBar" asp-action="SearchBar">SearchOption</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Reviews
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="PeopleReviews" asp-action="Reviews">Reviews</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                User Profile
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mvc_project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mvc-project/Views/UserLogin/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Mvc_project.ViewModel.LoginVM
@{
}
@if(ViewBag.errormessage != null)
{
    <h3> 
        @ViewBag.errormessage
    </h3>
}
else if(ViewBag.successmessage != null)
{
    <h3> 
        @ViewBag.successmessage
    </h3>
}
<div class="bg-secondary bg-opacity-10 py-3">
    <div class="container">
        <h2>You Can Easily Login To Your Accont Here</h2>
    </div>
</div>
<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="text" value="" class="form-control"  asp-for="UserEmail"/>
        </div>
        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="text" value="" class="form-control" asp-for="PasswordHash" />
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

Mvc-project/Views/UserRefistration/Registration.cshtml
@model Mvc_project.Models.Tables.Users
@{
}

<div class="bg-secondary bg-opacity-10 py-3">
    <div class="container">
        <h1>The New Users Can Register Themselves To This Website Here</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" value="" class="form-control" id="name" name="name" />
        </div>
        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="text" value="" class="form-control" id="email" name="email"/>
        </div>
        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="text" value="" class="form-control" id="password" name="password"/>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>